name: Clean workdlow

on:
  workflow_dispatch:

jobs:
  job_one:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd TestRepo
            git pull
