# This is a basic workflow to help you get started with Actions

name: deploy workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jobs-one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            cd ../
            cd ./pub/
            git pull
